name: akash
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  device_frame:
  google_fonts:
  iconly: ^1.0.1
  lottie: ^2.3.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_otp_text_field: ^1.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/

