name: akash
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_frame:
  get_storage: ^2.1.1
  google_fonts:
  iconly: ^1.0.1
  lottie: ^2.3.1
  get: 4.6.5
  image_picker: ^0.8.7+2
  jwt_decoder: ^2.0.1
  dropdown_button2: ^2.1.0
  intl:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  faker:
  flutter_svg: ^2.0.5
  flutter_dotenv: ^5.0.2
  razorpay_flutter: ^1.3.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
    - .env

